# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: reiinakano's blog
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I like building awesome things with awesome people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reiinakano.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ReiiYoda
github_username:  reiinakano

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/so-simple-theme"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

read_time: true
words_per_minute: 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: reiinakano
twitter:
  username: "ReiiYoda"

# Liquid
liquid:
  error_mode: strict


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/ReiiYoda
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/reiinakano
    icon: fab fa-github-square
